### ISSUE TITLE
Line numbers appended after code than at the start of each line on some posts

### ISSUE THREAD

**Issue by Zeeveez** [Cerbrus/userscripts#1]
On some questions on PPCG.SE the line numbers appear appended after the code, rather than inline with it. For example, the code:

```
x = 1
print(x)
```

would be expected to show:

```
1  x = 1
2  print(x)
```

but instead shows
```
   x = 1
   print(x)
   1
   2
```

Example screenshot taken from: https://codegolf.stackexchange.com/questions/263283/meta-cat-program

![image](https://github.com/Cerbrus/userscripts/assets/9338660/7d977c2c-a091-42a0-9aad-43659ee91b4f)

Another example: https://codegolf.stackexchange.com/questions/263308/make-a-k-skip-j-range

I haven't seen this occur on other sites.

Appears to be caused by these answers:
https://codegolf.stackexchange.com/a/263290/92232
https://codegolf.stackexchange.com/a/263340/92232

Exception is:

> TypeError: c.querySelector(...) is null

Due to no `<code>` being in those blocks.

**Comment by Cerbrus** [comment]
Thanks for the report!

Apparently, there were some user-created `<pre>` blocks on those pages, which caused the script to break.

I've filtered those out. Now it should work again.
